-- Core API functions implemented in Lua
dofile(DATA_DIRECTORY .. "/lib/core/load.lua")

-- Others library
dofile(DATA_DIRECTORY .. "/lib/others/load.lua")

-- Quests library
dofile(DATA_DIRECTORY .. "/lib/quests/quest.lua")

-- Tables library
dofile(DATA_DIRECTORY .. "/lib/tables/load.lua")

-- Functions library
dofile(DATA_DIRECTORY .. "/lib/functions/load.lua")

-- Pokemon catalogue (generated by `pnpm build-data`, Fase 2)
dofile(DATA_DIRECTORY .. "/lib/pokemon/catalog.lua")

-- Pokemon libraries (order matters: everything below consumes the catalogue)
dofile(DATA_DIRECTORY .. "/lib/pokemon/stats.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/effectiveness.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/damage.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/cooldown.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/instance.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/visual_ids.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/visual.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/look.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/summon.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/wild.lua")
dofile(DATA_DIRECTORY .. "/lib/pokemon/move.lua")
