-- A pokemon that is out of its ball cannot be traded.
--
-- The rule exists to close a real hole rather than to be tidy. Fainting runs
-- `transform`, and on the destructive path `transform` replaces the object
-- instead of mutating it -- while Canary holds the **pointer** to a traded
-- item in `tradeItems` (`game.cpp:5952`) and `player->tradeItem` (`:6184`).
-- A pokemon fainting mid-trade would leave those two pointing at an object
-- that is no longer in the world.
--
-- Fainting only happens to a pokemon that is out, so forbidding that one case
-- removes the whole scenario. Every minted id shares market category 9 and so
-- takes the in-place path anyway, which means this guard is the second lock
-- and not the only one -- but the first lock is a property of generated data,
-- and data gets regenerated by people who have not read the warning.
--
-- Guarded at both ends on purpose: refusing only the offer would let a player
-- offer the ball and *then* send the pokemon out.

local function activeUid(player)
	local entry = Pokemon.getActive(player)
	if not entry or not entry.item then
		return nil
	end
	local mon = Pokemon.read(entry.item)
	return mon and mon.uid or nil
end

--- Does this item, or anything inside it, hold the pokemon that is out?
--
-- Compares `pokemon_uid` rather than the item reference: the uid is the
-- identity this phase already maintains, and it survives the object being
-- replaced underneath us, which a reference does not.
local function carriesActive(item, uid)
	if not item or not uid then
		return false
	end
	if item:getCustomAttribute("pokemon_uid") == uid then
		return true
	end
	if not item:isContainer() then
		return false
	end
	-- `getItems(true)` is recursive, so a bag inside a bag is covered.
	for _, inner in ipairs(item:getItems(true) or {}) do
		if inner:getCustomAttribute("pokemon_uid") == uid then
			return true
		end
	end
	return false
end

local function refuse(player, item, uid)
	if not carriesActive(item, uid) then
		return false
	end
	player:sendTextMessage(MESSAGE_TRADE, "Put your pokemon back in its ball before trading it.")
	return true
end

local onRequest = EventCallback("PlayerOnTradeRequestPokemonGuard")

function onRequest.playerOnTradeRequest(player, target, item)
	return not refuse(player, item, activeUid(player))
end

onRequest:register()

local onAccept = EventCallback("PlayerOnTradeAcceptPokemonGuard")

function onAccept.playerOnTradeAccept(player, target, item, targetItem)
	-- Both sides, because either player may have sent a pokemon out between
	-- offering and accepting.
	local mine = refuse(player, item, activeUid(player))
	local theirs = refuse(target, targetItem, activeUid(target))
	return not (mine or theirs)
end

onAccept:register()
