-- A pokemon that is out of its ball cannot be traded.
--
-- The rule exists to close a real hole rather than to be tidy. Fainting runs
-- `transform`, and on the destructive path `transform` replaces the object
-- instead of mutating it -- while Canary holds the **pointer** to a traded
-- item in `tradeItems` (`game.cpp:5952`) and `player->tradeItem` (`:6184`).
-- A pokemon fainting mid-trade would leave those two pointing at an object
-- that is no longer in the world.
--
-- Fainting only happens to a pokemon that is out, so forbidding that one case
-- removes the whole scenario. Every minted id shares market category 9 and so
-- takes the in-place path anyway, which means this guard is the second lock
-- and not the only one -- but the first lock is a property of generated data,
-- and data gets regenerated by people who have not read the warning.
--
-- Guarded at both ends on purpose: refusing only the offer would let a player
-- offer the ball and *then* send the pokemon out.

local function refuse(player, item)
	local out = Pokemon.holdsActive(player, item)
	if not out then
		return false
	end
	player:sendTextMessage(MESSAGE_TRADE, string.format(
		"%s is at your side. Call it back before trading its ball.", out.species))
	return true
end

local onRequest = EventCallback("PlayerOnTradeRequestPokemonGuard")

function onRequest.playerOnTradeRequest(player, target, item)
	return not refuse(player, item)
end

onRequest:register()

local onAccept = EventCallback("PlayerOnTradeAcceptPokemonGuard")

function onAccept.playerOnTradeAccept(player, target, item, targetItem)
	-- Both sides, because either player may have sent a pokemon out between
	-- offering and accepting.
	local mine = refuse(player, item)
	local theirs = refuse(target, targetItem)
	return not (mine or theirs)
end

onAccept:register()
