-- Generated by tools/mint-balls.mjs. Do not edit by hand.
--
-- The four empty balls. Unlike the occupied ones these are multiuse and
-- stackable -- throwing IS "Use with ...", and balls are bought by the dozen.

PokemonBallItems = {
	["Poke Ball"] = 60304,
	["Great Ball"] = 60305,
	["Super Ball"] = 60306,
	["Ultra Ball"] = 60307,
}
