-- How likely a ball is to hold, and which balls exist.
--
-- The chance is a per-species TABLE, not a formula over `captureRate`: 55 of
-- the 154 species share `captureRate = 45`, and among the 44 of those with
-- solid measurement the real rate runs from 0.3% (Eevee) to 27.8% (Omanyte).
-- The field cannot tell them apart. `PokemonCatch` was seeded from the Roxy
-- production statistics -- see the phase 5 spec for the measurement.

Pokemon = Pokemon or {}

-- Hard failure rather than a nil the reads below would swallow. `PokemonCatch`
-- lives only in the generated `catalog.lua`, and without it `isCatchable`
-- answers false for EVERY species -- so a clean build would ship a game where
-- nothing is catchable and say "You cannot catch this pokemon.", the same
-- sentence a legendary gets, with nothing in the log. Same reasoning as the
-- assert at the bottom of scripts/actions/throw_ball.lua: a catalogue that did
-- not load is a broken install, not a case to degrade quietly through.
assert(PokemonCatch,
	"catch.lua: PokemonCatch is missing -- lib/pokemon/catalog.lua did not load. Regenerate it with `corepack pnpm build-data`")

-- One dial for the whole economy. 1.0 means literally "the economy the Roxy
-- ran": one capture every 11.2 balls, measured over 106,490 attempts.
Pokemon.CATCH_SCALE = 1.0

-- 3.5x from the worst ball to the best, which is the range both legacy bases
-- ran in (Roxy 2.2x, PokeMonster 8x). The value stored per species is the
-- GREAT ball's rate, not the Poke's: the measurement is aggregated over the
-- mix of balls players actually used, so anchoring it at the cheapest ball and
-- then multiplying up would count the good ball twice.
--
-- No `guaranteed` field: the Master Ball is out of the alpha, and a field no
-- row uses is the dead scaffolding the lessons doc says not to leave behind.
--
-- Written as a list keyed by ITEM NAME and turned into the id-keyed table
-- below, rather than indexing `PokemonBallItems` inline. Inline, renaming a
-- ball in `tools/mint-balls.mjs` puts nil in the key position, Lua raises
-- `table index is nil`, and this whole file aborts at load -- the same
-- silent-abort class documented at throw_ball.lua:32-44, where the server comes
-- up healthy and the feature is simply absent. The loop names the ball and the
-- generator instead.
local BALL_TIERS = {
	{ item = "Poke Ball", name = "poke ball", multiplier = 0.7 },
	{ item = "Great Ball", name = "great ball", multiplier = 1.0 },
	{ item = "Super Ball", name = "super ball", multiplier = 1.5 },
	{ item = "Ultra Ball", name = "ultra ball", multiplier = 2.5 },
}

Pokemon.BALLS = {}
for _, tier in ipairs(BALL_TIERS) do
	local itemId = PokemonBallItems and PokemonBallItems[tier.item]
	assert(itemId, string.format(
		"catch.lua: PokemonBallItems has no \"%s\" -- lib/pokemon/ball_ids.lua is generated by tools/mint-balls.mjs, and the name there must match the one here",
		tier.item))
	Pokemon.BALLS[itemId] = { name = tier.name, multiplier = tier.multiplier }
end

--- Is this species catchable at all?
--
-- Impossible is a STATE, not a very small number. Legendaries are event
-- content and the baby forms come from Oak in phase 7; both refuse before
-- anything is consumed. Reading the state rather than testing `rate == 0`
-- matters because a measured zero is a different thing: `Aerodactyl` really
-- did go 0 for 326 on the Roxy, and it is meant to be brutal, not forbidden.
-- A species absent from a LOADED table is a real refusal (nothing in the
-- catalogue says it can be caught); a missing table is not, and the assert at
-- the top is what keeps the two apart.
function Pokemon.isCatchable(species)
	local entry = PokemonCatch[species]
	if not entry then
		return false
	end
	return entry.source ~= "impossible"
end

--- Chance of this ball holding this species, from 0 to 1.
--
-- @param bonuses list of fractions, e.g. {0.1} for +10%. Empty today; Premium
--        and the future equipment and mastery bonuses land here. It is a
--        parameter and not a flag on purpose -- an empty list that gets
--        iterated cannot become the "read but never written" bug the lessons
--        doc catalogues.
function Pokemon.catchChance(species, ballItemId, bonuses)
	local entry = PokemonCatch[species]
	if not entry then
		error("unknown species in the catch table: " .. tostring(species))
	end

	local ball = Pokemon.BALLS[ballItemId]
	if not ball then
		error("unknown ball item: " .. tostring(ballItemId))
	end

	local chance = entry.rate * ball.multiplier * Pokemon.CATCH_SCALE
	for _, b in ipairs(bonuses or {}) do
		chance = chance * (1 + b)
	end

	return math.min(1.0, math.max(0.0, chance))
end
