-- Which sprite a ball shows: species and state, expressed as the item id.
--
-- The client never sees a custom attribute. It sees an item id and draws
-- whatever the appearances file says that id looks like. So "show a fainted
-- Charizard" is not a message we can send -- it is an item id we have to
-- become, and changing it is `transform`.
--
-- The ids come from `visual_ids.lua`, generated by `tools/mint-visuals.mjs`
-- out of the Roxy artwork. 152 of the 154 species have one; Paras and Seel
-- have no icon in that pack and keep the placeholder ball.

Pokemon = Pokemon or {}

--- The item id for a species in a state, or nil when the art is missing.
-- @param state "alive" or "fainted"
function Pokemon.visualId(species, state)
	local entry = PokemonVisual and PokemonVisual[species]
	if not entry then
		return nil
	end
	return state == "fainted" and entry.fainted or entry.alive
end

--- The id this item *should* have, given what is inside it.
function Pokemon.wantedVisual(mon)
	return Pokemon.visualId(mon.species, mon.fainted and "fainted" or "alive")
end

--- Bring the item's id in line with its contents.
--
-- @return the item. **May be a different object** than the one passed in, so
--         callers have to use the return value rather than the reference they
--         already hold.
function Pokemon.syncVisual(item)
	local mon = Pokemon.read(item)
	if not mon then
		return item
	end

	local wanted = Pokemon.wantedVisual(mon)
	-- No art for this species yet: leave it on whatever it is rather than
	-- transform it to nil and lose the pokemon.
	if not wanted or item:getId() == wanted then
		return item
	end

	-- Save and rewrite unconditionally. `transform` keeps the attributes when
	-- both ids share `ItemType::type` and drops them when they do not
	-- (measured, appendix B) -- every id minted here carries market category 9
	-- precisely so the first case holds, but rewriting anyway makes this
	-- correct even if someone later changes a category without reading the
	-- warning. It costs six attribute writes on a transition that happens
	-- twice in a pokemon's life.
	local saved = Pokemon.snapshot(item)
	item:transform(wanted)
	Pokemon.restore(item, saved)
	return item
end
